### ISSUE TITLE
NoName HideTool

### ISSUE THREAD

**Issue by Juulsn** [Simonsator/BungeecordPartyAndFriends#11]
Hey, bin gerade dabei das Plugin zu configurieren.
Hab dabei gemerkt dass das HideItem keinen Namen hat.
Hab mal deinen Code decompiled, und siehe da: 
unter de/simonsator/partyandfriendsgui/manager/ItemManager.java
fand ich das:

string = "Inventories.SettingsMenu.PlaceHolderItem.";
this.SETTINGS_MENU_PLACEHOLDER = configuration.getBoolean(string + "Use") ? itemManagerSetupHelper.getItemStack(TextIdentifier.FRIEND_ACCEPT_MENU_PLACEHOLDER, string + "ItemData", string + "MetaData") : null;
string = "Inventories.ToolBar.HideItem.";
this.**HIDE_ITEM** = configuration.getBoolean(string + "Use") ? itemManagerSetupHelper.getItemStack(# TextIdentifier.**FRIEND_ACCEPT_MENU_PLACEHOLDER**, string + "ItemData", string + "MetaData") : null;

ich habs für mich jetzt selber gefixed, aber für die anderen solltest du das im nächsten update fixen :D

LG Julian

**Comment by Simonsator** [comment]
Das ist der falsche platz um dies zu Posten. Das ist nicht die extended version. Zweitens darfst du eigentlich nicht PAF decompilen du darfst nur den Zugang zur repo beantragen.

**Comment by Juulsn** [comment]
Ich weiß aber was hätt ich tun sollen :D 
und denn Zugang hab ich schon beantragt^^

**Comment by Simonsator** [comment]
Warten bis du den Zugang hast. Und niemand interessiert es, dass du etwas nicht erlaubt es machst bist du es erzählst
