### ISSUE TITLE
Suggestion: Velocity Support

### ISSUE THREAD

**Issue by austin4195** [Simonsator/BungeecordPartyAndFriends#17]
As the title suggests, adding Velocity support would be helpful in boosting the platform and open this plugin up to a new audience!

**Comment by Simonsator** [comment]
Porting over party and friends to velocity would take even more work than porting it to spigot took, as the api is much different and it would be harder to commit future changes from the bungeecord version to the velocity version. Also all extensions would need a new version to support velocity. I am able to make most extensions also support spigot without having to change to much as the spigot and bungeecord api are very similar. This is not that easy possible with velocity.

And another point is that I know nearly nothing about the velocity api and I would have to learn it first and it ain't documented as good as the bungeecord or spigot api.

The third reason that at least currently I will not (at least currently) create a velocity version is that they don't have a premium plugin section at the moment and as it would take much work to port it I would charge money for the port (people who already bought it on spigot would get free access to the port), which is currently not possible.
