### ISSUE TITLE
Text of /fmsg does not contain spaces

### ISSUE THREAD

**Issue by LorenzoSimone02** [Simonsator/BungeecordPartyAndFriends#20]
In the version 1.0.81 i found this issue:
The command /fmsg Player Hello World!
Return "HelloWorld!" to the player who recieves the message instead of "Hello World!.
When the arguments of the command are attached to create the message the spaces are missing.

![2020-11-10_16 28 48](https://user-images.githubusercontent.com/15893018/98694608-f1cdb900-2371-11eb-929a-0f4102cd52b7.png)

**Comment by Simonsator** [comment]
You are missing a space in the messages.yml under "Friends.Command.MSG.ColorOfMessage"
