### ISSUE TITLE
UpdateChecker missing

### ISSUE THREAD

**Issue by Matix-Media** [Simonsator/BungeecordPartyAndFriends#21]
Hi, I am currently trying to build the plugin from source, but Maven tells me, that he can't find de.simonsator:UpdateChecker

And I don't know either where to find it.

Can someone help me out?
Thanks in advice.

**Comment by Simonsator** [comment]
Try to use http instead of https for the simonsator repo.

**Comment by Matix-Media** [comment]
So in intellij create new from version control > http://github.com/Simonsator/BungeecordPartyAndFriends.git
Right?

**Comment by Simonsator** [comment]
No. The change needs to be made in line 82 of the pom.xml.

**Comment by Matix-Media** [comment]
Thank you! Everything is working now!
