### ISSUE TITLE
Update  uuid player in database

### ISSUE THREAD

**Issue by kacpiklPL** [Simonsator/BungeecordPartyAndFriends#26]
Welcome

I noticed you have a problem that you are not updating UUID player. When the player first enters the server, you add them to the table 'fr_players' with player_name and player_uuid. 

When a player buys a premium account in minecraft, the uuid changes. 
When i get PAFPlayer PartyManager.getInstance().getPlayer(uuid) returns me null, because cannot find a player with this uuid in "fr_players".

I solved it by doing update player_uuid during AsyncPlayerPreLoginEvent (event.getUniqueId())

**Comment by Simonsator** [comment]
Thank you for informing me about this. 

The bugfix is now implemented in the source code of the extended version and will be back ported with the next release of the free version.
