### ISSUE TITLE
Party Deleted Event

### ISSUE THREAD

**Issue by PikaMug** [Simonsator/BungeecordPartyAndFriends#28]
**Is your feature request related to a problem? Please describe.**
There is no event for catching the destruction of a PlayerParty.

**Describe the solution you'd like**
Add such an event under https://github.com/Simonsator/BungeecordPartyAndFriends/tree/master/src/main/java/de/simonsator/partyandfriends/api/events/party

**Describe alternatives you've considered**
None.

**Additional context**
So that https://github.com/PikaMug/Unite might be able to support this.

**Comment by Simonsator** [comment]
Use the `LeftPartyEvent` and check if the party has no leader and no party members. In that case, it is going to be deleted.
