### ISSUE TITLE
Disable hide player module in specific servers or worlds

### ISSUE THREAD

**Issue by WitheredWinter** [Simonsator/BungeecordPartyAndFriends#29]
**Is your feature request related to a problem? Please describe.**
Yes.In the survival server,my players can use the hide player module and ignore someone.Then they can place blocks at that player's location,which causes the player being blocked in walls and suffer damage.
So i want an option to disable hide player module in specific servers.

**Describe the solution you'd like**
I want an option to disable hide player module in specific servers.It's not just ban the command /hide.I prefer to everyone is forced to see every player.

**Describe alternatives you've considered**
Ban the /hide and /hidegui,then force everyone to stay in "show all player"state.

**Additional context**
I am willing to help you test the new feature if you need my help.You can contact me through Discord.I am DreamStarσ#0440

**Comment by Simonsator** [comment]
Disable both the hide command and hide item on a server to deactivate the hide mode.

**Comment by WitheredWinter** [comment]
That works!thank you!
