### ISSUE TITLE
ChatColor & -> §

### ISSUE THREAD

**Issue by navopw** [Simonsator/BungeecordPartyAndFriends#3]
Please use

`textToTranslate = ChatColor.translateAlternateColorCodes('&', textToTranslate);`

instead of

`.replace("&", "§");`

~Navo

**Comment by navopw** [comment]
Especially in MessagesYML

**Comment by Simonsator** [comment]
What is the advantage of that method?

**Comment by navopw** [comment]
When you use the color "&x" (which doesn't exist), it will not be translated :smile:

**Comment by Simonsator** [comment]
Fixed in [1.0.29](https://github.com/Simonsator/BungeecordPartyAndFriends/commit/90a239f00698d01d170d511b1cd353df43022a47)
