### ISSUE TITLE
2 "cosmetic" killer-features! They are very useful and helping to determine friends from other players easy

### ISSUE THREAD

**Issue by ChefMC** [Simonsator/BungeecordPartyAndFriends#31]
And add 2 very useful "cosmetic" features:

1) Color friends nametags as blue (&9) like on Shotbow Network. Player nicknames are blue above head, in tab, in chat and everywhere else. Especially on PvP servers it will be much easier to react in milliseconds on enemies and separate them from friends. Friends will be instantly casted as players just by their calm blue nametag. So if nametag of another players is white - this means it's not your friend and you should be instantly noticed about that to react on that possible enemy;

2) Literally highlight your friends (simulating spectral arrow effect). So you will see your friends or your team even through walls and will not lost each other. To change color of spectral highlighting, change Scoreboard prefix color: better to implement that as Placeholder way to make compatibility with existing prefixes of players which are handled by multiple other plugins

**Comment by Simonsator** [comment]
I don't think this is possible using the Bungeecord api. This would have to be a seperate plugin which uses the Friends API for spigot plugins.

**Comment by NDruce** [comment]
So then make it this way. I posted this to BungeeCord only because there is needed to support this feature also across servers
