### ISSUE TITLE
Spaces get removed in private messages

### ISSUE THREAD

**Issue by ricardoboss** [Simonsator/BungeecordPartyAndFriends#5]
When a user sends a private message to one of his friends, the spaces get removed from the final message. I tried editing the code after cloning the master branch, but I couldn't get it to work.

Maybe it has to do with the last commit: [fixed bugs](https://github.com/Simonsator/BungeecordPartyAndFriends/commit/568338fee2c0188844625cb0a64ac6cf2a13401d)

**Comment by Simonsator** [comment]
That is not caused by the plugin directly. It is caused by the language file that you are using. In the value "Friends.MSG.ColorOfMessage" is a space missing.
