### ISSUE TITLE
Can't translate Friends.Command.MSG.SentMessage

### ISSUE THREAD

**Issue by MineTheCube** [Simonsator/BungeecordPartyAndFriends#7]
Hi,

I've a strange bug, each time I change the message `Friends.Command.MSG.SentMessage` in Messages.yml, it get replaced by original value: `&e[SENDERNAME]&5-> &e[PLAYER]&7: [CONTENT]`.

I translated every other line without any issues, but this won't work...

**Comment by Simonsator** [comment]
You are not using the newest version.
