### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by MCG-server** [Simonsator/BungeecordPartyAndFriends#9]
Hello ! I have some questions I put the plug in the right folder, but when I do the command / party or / friend tells me that the command does not exist .. why ??
(Use the latest version of the plugin instead bungeecord is 1.8)

necessarily have to use mysql ?? if you tell me how to download it on my computer or some site that sells mysql services

**Comment by Simonsator** [comment]
Yes you need MySQL. Check this out https://www.mysql.com
